import { useState } from "react";
import { AlertTriangle, Plus, Trash2 } from "lucide-react";
import { useProject } from "@/store/project-store";
import type { TimelineEvent } from "@/lib/types";
import { analyzeEventImpact } from "@/lib/timeline-graph";

export function DayOfPanel() {
  const { project, updateEntity, addEntity, removeEntity, canEdit } = useProject();
  const [pending, setPending] = useState<{ id: string; patch: Partial<TimelineEvent> }>();
  if (!project) return null;
  const events = project.timeline.filter(event => event.phase === "pendant").sort((a, b) => a.time - b.time);
  const impact = pending ? analyzeEventImpact(project, pending.id, pending.patch) : undefined;
  const propose = (id: string, patch: Partial<TimelineEvent>) => setPending({ id, patch });
  return <div className="mx-auto max-w-4xl space-y-4 pb-10"><div className="flex items-center justify-between"><div><h4 className="text-2xl font-display font-light">Le déroulé du Jour J</h4><p className="text-sm text-white/40">Les changements structurants sont prévisualisés avant application.</p></div>{canEdit && <button onClick={() => addEntity("timeline", { time: project.pivot.value, durationMinutes: 60, kind: "evenement", title: "Nouveau temps fort", status: "prepare", confidence: "confirme", phase: "pendant", universe: project.universe, provenance: "real", visibility: "equipe", relations: [], dependencyIds: [], resources: [] })} className="rounded-full border border-white/15 px-3 py-2 text-xs"><Plus className="mr-1 inline h-3 w-3" />Ajouter</button>}</div>
    {events.map(event => <div key={event.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex gap-2"><input disabled={!canEdit} type="time" value={new Date(event.time).toTimeString().slice(0, 5)} onChange={e => { const [hours, minutes] = e.target.value.split(":").map(Number); const date = new Date(event.time); date.setHours(hours, minutes, 0, 0); propose(event.id, { time: date.getTime() }); }} className="rounded-lg bg-white/10 p-2 text-sm" /><input disabled={!canEdit} value={event.title} onChange={e => updateEntity("timeline", event.id, { title: e.target.value })} className="min-w-0 flex-1 bg-transparent text-sm outline-none" />{canEdit && <button onClick={() => removeEntity("timeline", event.id)}><Trash2 className="h-4 w-4 text-white/25" /></button>}</div>
      <div className="mt-3 grid grid-cols-3 gap-2"><input disabled={!canEdit} value={event.location || ""} onChange={e => propose(event.id, { location: e.target.value })} placeholder="Lieu" className="rounded-lg bg-white/10 p-2 text-xs outline-none" /><input disabled={!canEdit} type="number" min="0" value={event.durationMinutes || 0} onChange={e => propose(event.id, { durationMinutes: Number(e.target.value) })} className="rounded-lg bg-white/10 p-2 text-xs" /><select disabled={!canEdit} value={event.status} onChange={e => updateEntity("timeline", event.id, { status: e.target.value })} className="rounded-lg bg-white/10 p-2 text-xs"><option value="prepare">À préparer</option><option value="execute">Terminé</option><option value="bloque">Bloqué</option></select></div>
    </div>)}
    {pending && impact && <div className="fixed inset-x-4 bottom-24 z-50 mx-auto max-w-xl rounded-2xl border border-amber-300/25 bg-[#17140c] p-4 shadow-2xl"><p className="flex items-center gap-2 text-sm font-medium text-amber-200"><AlertTriangle className="h-4 w-4" />Prévisualisation requise</p><p className="mt-2 text-xs text-white/60">{impact.changed.join(", ")} · {impact.relations.length} entité(s) liée(s) · {impact.dependents.length} dépendance(s)</p>{impact.conflicts.map(conflict => <p key={conflict.message} className="mt-1 text-xs text-rose-300">{conflict.message}</p>)}<p className="mt-2 text-[10px] text-white/35">Les entités liées et dépendances ne seront jamais déplacées silencieusement.</p><div className="mt-3 flex gap-2"><button onClick={() => { updateEntity("timeline", pending.id, { ...pending.patch, propagation: { state: "applied", lastAppliedAt: Date.now(), sourceEventId: pending.id } }); setPending(undefined); }} className="rounded-full bg-white px-3 py-1.5 text-xs text-black">Appliquer à l’événement seul</button><button onClick={() => setPending(undefined)} className="rounded-full border border-white/15 px-3 py-1.5 text-xs">Annuler</button></div></div>}
  </div>;
}