import { useState } from "react";
import { useProject } from "@/store/project-store";
import { Plus, Search, Trash2 } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Provider } from "@/lib/types";

export function ProviderPanel() {
  const { project, updateEntity, addEntity, removeEntity } = useProject();
  const [query, setQuery] = useState("");
  if (!project) return null;
  const providers = project.providers.filter(p => `${p.role} ${p.name || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="mx-auto max-w-4xl space-y-5"><div className="flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3"><Search className="h-3.5 w-3.5 text-white/40" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher un prestataire…" className="w-full bg-transparent py-2 text-sm outline-none" /></div><button onClick={() => addEntity("providers", { role: "Nouveau poste", category: "autre", status: "recherche", nextAction: "Ajouter un contact" })} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-3 text-xs hover:bg-white hover:text-black"><Plus className="h-3.5 w-3.5" />Ajouter</button></div><div className="grid gap-3 pb-10 md:grid-cols-2">{providers.length === 0 ? <div className="md:col-span-2 rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-white/40">Aucun prestataire trouvé.</div> : providers.map(provider => <ProviderRow key={provider.id} provider={provider} onEdit={u => updateEntity("providers", provider.id, u)} onDelete={() => removeEntity("providers", provider.id)} />)}</div></div>;
}

function ProviderRow({ provider, onEdit, onDelete }: { provider: Provider; onEdit: (u: Partial<Provider>) => void; onDelete: () => void }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-start gap-3"><div className="flex-1"><input value={provider.role} onChange={e => onEdit({ role: e.target.value })} className="w-full bg-transparent text-[10px] uppercase tracking-widest text-white/50 outline-none" /><input value={provider.name || ""} onChange={e => onEdit({ name: e.target.value })} placeholder="Nom du prestataire" className="mt-1 w-full bg-transparent text-base font-medium outline-none placeholder:text-white/30" /></div><button onClick={onDelete} className="text-white/25 hover:text-rose-300"><Trash2 className="h-4 w-4" /></button></div><div className="mt-4 grid grid-cols-2 gap-2"><select value={provider.status} onChange={e => onEdit({ status: e.target.value as Provider["status"] })} className="rounded-lg bg-white/10 px-2 py-2 text-xs outline-none"><option value="recherche">Recherche</option><option value="contacte">Contacté</option><option value="rencontre">Rencontré</option><option value="devis">Devis</option><option value="reserve">Réservé / payé</option></select><input value={provider.contact || ""} onChange={e => onEdit({ contact: e.target.value })} placeholder="Contact" className="rounded-lg bg-white/10 px-2 py-2 text-xs outline-none" /><input type="number" value={(provider.amountCents || 0) / 100} onChange={e => onEdit({ amountCents: Number(e.target.value) * 100 })} placeholder="Devis €" className="rounded-lg bg-white/10 px-2 py-2 text-xs outline-none" /><input value={provider.nextAction || ""} onChange={e => onEdit({ nextAction: e.target.value })} placeholder="Prochaine action" className="rounded-lg bg-white/10 px-2 py-2 text-xs outline-none" /></div><div className={cn("mt-3 text-[10px] uppercase tracking-widest", provider.status === "reserve" ? "text-emerald-300" : provider.status === "recherche" ? "text-amber-300" : "text-white/40")}>{provider.status}</div></div>;
}